export const ALLOCATE_CLASSROOM = "ALLOCATE_CLASSROOM";
export const ALLOCATE_CLASSROOM_SUCCESS = "ALLOCATE_CLASSROOM_SUCCESS";
export const ALLOCATE_CLASSROOM_FAIL = "ALLOCATE_CLASSROOM_FAIL";

export const DEALLOCATE_CLASSROOM = "DEALLOCATE_CLASSROOM";
export const DEALLOCATE_CLASSROOM_SUCCESS = "DEALLOCATE_CLASSROOM_SUCCESS";
export const DEALLOCATE_CLASSROOM_FAIL = "DEALLOCATE_CLASSROOM_FAIL";

export const ALLOCATE_SUBJECT = "ALLOCATE_SUBJECT";
export const ALLOCATE_SUBJECT_SUCCESS = "ALLOCATE_SUBJECT_SUCCESS";
export const ALLOCATE_SUBJECT_FAIL = "ALLOCATE_SUBJECT_FAIL";

export const DEALLOCATE_SUBJECT = "DEALLOCATE_SUBJECT";
export const DEALLOCATE_SUBJECT_SUCCESS = "DEALLOCATE_SUBJECT_SUCCESS";
export const DEALLOCATE_SUBJECT_FAIL = "DEALLOCATE_SUBJECT_FAIL";
