export const ADD_TEACHER = "ADD_TEACHER";
export const ADD_TEACHER_SUCCESS = "ADD_TEACHER_SUCCESS";
export const ADD_TEACHER_FAIL = "ADD_TEACHER_FAIL";

export const GET_ALL_TEACHER = "GET_ALL_TEACHER";
export const GET_ALL_TEACHER_SUCCESS = "GET_ALL_TEACHER_SUCCESS";
export const GET_ALL_TEACHER_FAIL = "GET_ALL_TEACHER_FAIL";

export const GET_ALL_ALLOCATE_CLASS = "GET_ALL_ALLOCATE_CLASS";
export const GET_ALL_ALLOCATE_CLASS_SUCCESS = "GET_ALL_ALLOCATE_CLASS_SUCCESS";
export const GET_ALL_ALLOCATE_CLASS_FAIL = "GET_ALL_ALLOCATE_CLASS_FAIL";

export const GET_ALL_ALLOCATE_SUBJECT = "GET_ALL_ALLOCATE_SUBJECT";
export const GET_ALL_ALLOCATE_SUBJECT_SUCCESS =
  "GET_ALL_ALLOCATE_SUBJECT_SUCCESS";
export const GET_ALL_ALLOCATE_SUBJECT_FAIL = "GET_ALL_ALLOCATE_SUBJECT_FAIL";
