export const ADD_SUBJECT = "ADD_SUBJECT";
export const ADD_SUBJECT_SUCCESS = "ADD_SUBJECT_SUCCESS";
export const ADD_SUBJECT_FAIL = "ADD_SUBJECT_FAIL";

export const GET_ALL_SUBJECT = "GET_ALL_SUBJECT";
export const GET_ALL_SUBJECT_SUCCESS = "GET_ALL_SUBJECT_SUCCESS";
export const GET_ALL_SUBJECT_FAIL = "GET_ALL_SUBJECT_FAIL";
