export const ADD_CLASSROOM = "ADD_CLASSROOM";
export const ADD_CLASSROOM_SUCCESS = "ADD_CLASSROOM_SUCCESS";
export const ADD_CLASSROOM_FAIL = "ADD_CLASSROOM_FAIL";

export const GET_CLASSROOM = "GET_CLASSROOM";
export const GET_CLASSROOM_SUCCESS = "GET_CLASSROOM_SUCCESS";
export const GET_CLASSROOM_FAIL = "GET_CLASSROOM_FAIL";
